# Introduction to Python for Science

**Cristobal Donoso**<br>
Department of Computer Science<br>
University of Concepcion, CHILE <br>
cridonoso@inf.udec.cl<br>
September 2018

### What's Python?
Python is a semi-interpreted language created by Guido van Rossum in late 80s. It is a perfect language that offers a wide set of packages for:
- get and Manipulate data
- visualice data
- make basis and complex maths
- much more!

Furthermore, Python brings you a beautiful syntax which allow you to move quickly and orderly (intuitive code, familiar to human language).

<img style="float: right;" src='https://developerencoma.files.wordpress.com/2013/01/languages_popularity_1110.png?w=580' width="500" height="600"> 
<img style="float: left;" src='https://lamiradadelreplicante.com/wp-content/uploads/2014/07/python-universidad.jpg' width="500" height="600"> 


### Table of Contents
-  **Coding basis with Python** 
    - Variables and Types of data
    - If-else sentences and Loops 
    - Functions
- **Numerical data with Numpy**
    - Arrays
    - Operations
    - Advanced Operations
    
- **Plotting with Matplotlib**
    - Kinds of plots
    - Figures, subplots, axis and ticks 

### Coding basis with Python
The first step in any programming language is to display a message from an input in the screen. So, the principal function to do this is ```print()```. You could input the message in many ways but... wait for it 

In [9]:
print('Hello World\n') #Simple text to display
print('Peace Between Worlds')
print('Hello', 'World', 155)

Hello World

Peace Between Worlds
Hello World 155


```print()``` function is very usefull and I'm sure it will be your favorite debugger in the future.<br><br>As we said before you could input the message (to display) in many ways, but What kind of message could you show on the screen?. In most of time you will use **variables** - and of course it can be printed.<br><br>A **variable**, as in maths, is an abstraction of something that will be used. In computer science, a variable is a portion of principal memory which will be used to save data.

In [13]:
# we defined a variable by named it with a word o character (You cannot use numbers or symbols like &, /, %, ., ?, etc.)
variable = 'Hola'   # we initialized with a data of kind STRING
variable2 = 23      # we initialized with a data of kind INT
variable3 = 23.9    # we initialized with a data of kind FLOAT
variable = 'Chao'   # we can replace the data in some variable by assigning a new value

We could initialize a variable with an operation.

In [21]:
# Defining initial values
a = 20
b = 4

#Defining operations using variables
add = a + b
sub = a - b
mul = a * b
div1 = a / b
div2 = a // b #FLOOR
mod = a % b

#Printting variables
print('Addition:', add)
print('Subtraction:', sub)
print('Multiplication:', mul)
print('Division:', div1)
print('Division:', div2)
print('Modulo:', mod)

Addition: 24
Subtraction: 16
Multiplication: 80
Division: 5.0
Division: 5
Modulo: 0


In python programs it's common to use **lists**. Lists are a special type of data that organizes different types of data.  

In [26]:
my_list = ['Car', 23, 'kitten', [1,2,3], div2] #notice that we initialized a list with square brackets
print('My list: ',my_list)

My list:  ['Car', 23, 'kitten', [1, 2, 3], 5]


There are [many operations with lists](https://docs.python.org/3/tutorial/datastructures.html). The main ones are:
- append
- indexing 
- sort
- del

In [39]:
my_new_list = [] # we initialized an empty list
my_new_list.append('My first data in the list')
print (my_new_list)
my_new_list.append('It is the second data in the list')
print (my_new_list)
my_new_list.append(10+10)
print (my_new_list)
my_new_list.append([1,2,'hola',['A list of list of list', 7]])
print (my_new_list)

['My first data in the list']
['My first data in the list', 'It is the second data in the list']
['My first data in the list', 'It is the second data in the list', 20]
['My first data in the list', 'It is the second data in the list', 20, [1, 2, 'hola', ['A list of list of list', 7]]]


In [46]:
#Indexing
first_item = my_new_list[0]
last_item = my_new_list[-1]
range_of_items = my_new_list[0:2]
print(first_item)
print(last_item)
print(range_of_items)
#The last item in the list in the list in the list
this = my_new_list[-1][-1][-1]
print('Latest value: ',this)

My first data in the list
[1, 2, 'hola', ['A list of list of list', 7]]
['My first data in the list', 'It is the second data in the list']
Latest value:  7


In [57]:
another_list = [2,6,8,2,8]
print(another_list)
another_list.sort()
print(another_list)

[2, 6, 8, 2, 8]
[2, 2, 6, 8, 8]


In [59]:
print(another_list)
del another_list[-1]
print(another_list)

[2, 2, 6, 8]
[2, 2, 6]


Since we know the list concept we could need to move along the elements of this. We can do this with **Loops** 

In [66]:
# going through the elements
for element in my_new_list:
    print(element)
# enumerating the elements
print('*'*50)
for i, element in enumerate(my_new_list):
    print(i,'.-', element)
# using a for statment to display a range
print('*'*50)
for k in range(0, 5):
    print(k)
# Size of list
print('*'*50)
print('Lenght of list: ',len(my_new_list))

My first data in the list
It is the second data in the list
20
[1, 2, 'hola', ['A list of list of list', 7]]
**************************************************
0 .- My first data in the list
1 .- It is the second data in the list
2 .- 20
3 .- [1, 2, 'hola', ['A list of list of list', 7]]
**************************************************
0
1
2
3
4
**************************************************
Lenght of list:  4


In order to work in specific domains, we can filter variables using **ifs** statments. The relational operators to make comparassion are:

In [69]:
# Relational Operators
a = 99
b = 10.2
 
# a > b 
print(a > b)
# a < b 
print(a < b)
# a == b 
print(a == b)
# a != b
print(a != b)
# a >= b
print(a >= b)
# a <= b
print(a <= b)

True
False
False
True
True
False


##### Exercise:  Write a program that iterates over a list from 0 to 10 and select the even values

In [70]:
# Your code here ! 

### Functions
Lets imagine that you need to define a VIPO (**V**ery **I**mportant **P**articular **O**peration). Probably, you will need to use this many time in your code but python didn't implement it for you :(<br><br>There is an special structure in python which allow you to write block of code which will be "calleable" whenever you want: **FUNCTIONS**

In [71]:
def exctract_odds(some_list):
    odds = []
    for value in some_list: 
        if value % 2 == 1:
            odds.append(value)
    return odds

In [73]:
whole = [1,2,3,4,5,6,7]
odds  = exctract_odds(whole)
print(odds)

[1, 3, 5, 7]


## NUMPY 
NumPy provides:	
- extension package to Python for multi-dimensional arrays
- closer to hardware (efficiency)
- designed for scientific computation (convenience)
- Also known as array oriented computing


For example, An array containing:

- values of an experiment/simulation at discrete time steps
- signal recorded by a measurement device, e.g. sound wave
- pixels of an image, grey-level or colour
- 3-D data measured at different X-Y-Z positions, e.g. MRI scan

(This list was extracted from [scipy-lectures](https://www.scipy-lectures.org/intro/numpy/array_object.html))<br>
(You can see more [here](https://docs.scipy.org/doc/numpy/user/quickstart.html))

In [74]:
import numpy as np

In [75]:
list_python = range(1000)
%timeit [i**2 for i in list_python]
numpy_array = np.arange(1000)
%timeit numpy_array**2

200 µs ± 2.51 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
938 ns ± 5.05 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


We can define multidimnesional arrays *by hand* or *pre-defined*. 

In [93]:
# Defining numpy arrays by hand
n = np.array([1,2,3])
m = np.array([[1,2,3.6],[4,5,6]])
l = np.array([[[1,2,3],
               [4,5,6]],
              [[1,2,3.6],
               [4,5,None]]])
print(n)
print(m)
print(l)
print('dimension of n:',n.ndim,'data type:',n.dtype)
print('dimension of m:',m.ndim,'data type:',m.dtype)
print('dimension of l:',l.ndim,'data type:',l.dtype)

[1 2 3]
[[1.  2.  3.6]
 [4.  5.  6. ]]
[[[1 2 3]
  [4 5 6]]

 [[1 2 3.6]
  [4 5 None]]]
dimension of n: 1 data type: int64
dimension of m: 2 data type: float64
dimension of l: 3 data type: object


In [117]:
# Pre-defined by NumPy
o = np.ones(5)
print('*'*50)
print(o)
y = np.ones([5,2])
print('*'*50)
print(y)
z = np.zeros(5)
print('*'*50)
print(z)
#Normal distribution
b = np.random.randn(2,2,2)
print('*'*50)
print(b)

**************************************************
[1. 1. 1. 1. 1.]
**************************************************
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
**************************************************
[0. 0. 0. 0. 0.]
**************************************************
[[[-0.34214883  2.30775842]
  [ 0.89075805 -1.59898619]]

 [[-0.12949103 -1.03694146]
  [-0.02239607 -2.0801838 ]]]


We can create range of values defined by bounds

In [125]:
a = np.arange(10)
print (a)
b = np.linspace(5,15,5,endpoint=False)
print (b)

[0 1 2 3 4 5 6 7 8 9]
[ 5.  7.  9. 11. 13.]


One of the advantages of working with NumPy is the operations which we can do between arrays, for example:

In [136]:
a = np.ones(4)
b = np.ones(4)
print(a)
x = np.sum([a,b], axis=0)
y = np.divide(a, 5)

[1. 1. 1. 1.]


In [137]:
print(x)
print(y)

[2. 2. 2. 2.]
[0.2 0.2 0.2 0.2]
